os: linux
dist: bionic
language: generic
sudo: required
git:
  depth: 1
addons:
  apt:
    update:
      - true
    packages:
      - wput
services:
  - docker
before_install:
  - docker pull fr3akyphantom/droid-builder:latest
install: true
before_script:
  - "travis_wait 20 sleep 1800 &"
  - mkdir -p $HOME/twrp && cd $HOME/twrp
  - wget -q https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.2.3-20180830/MinimalOmniRecovery-twrp-6.0-norepo-20180830.tar.xz
    -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - "travis_wait 20 sleep 1800 &"
  - cd $HOME/twrp/
  - git clone https://github.com/rokibhasansagar/twrp_device_Micromax_E453 -b master --single-branch device/Micromax/E453
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$HOME/.ccache:/srv/ccache:rw" -v "$(pwd):/home/builder/twrp/:rw,z" fr3akyphantom/droid-builder:latest bash << EOF
    cd /home/builder/twrp/
    source build/envsetup.sh
    lunch omni_E453-userdebug
    mka recoveryimage | tee build.log
    exit
    EOF
after_success:
  - cd $HOME/twrp/
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2) && echo "TWRP $version"
  - export nowTime=$(date +%Y%m%d-%H%M) && echo $nowTime
  - cp $HOME/twrp/out/target/product/E453/recovery.img $HOME/twrp/TWRP-$version-E453-$nowTime-Unofficial.img
  - cd $HOME/twrp/out/target/product/E453/system/
  - tar -I pxz -cf $HOME/twrp/extra-system-files-$nowTime.tar.xz *
  - cd $HOME/twrp/
  - #curl -s --upload-file TWRP-$version-Primo_RX5-$(date +"%Y%m%d")-Unofficial.img https://transfer.sh/ && echo ""
  - wput TWRP-$version-Primo_RX5-$nowTime-Unofficial.img ftp://"$FTPUser":"$FTPPass"@"$FTPHost"//TWBuild-$version-$nowTime/
  - wput extra-system-files-$nowTime.tar.xz ftp://"$FTPUser":"$FTPPass"@"$FTPHost"//TWBuild-$version-$nowTime/
  - cp $HOME/twrp/build.log $HOME/twrp/E453-$nowTime-build.log
  - wput extra-system-files-$nowTime.tar.xz ftp://"$FTPUser":"$FTPPass"@"$FTPHost"//TWBuild-$version-$nowTime/
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GitOAUTHToken
  file_glob: true
  file: $HOME/twrp/*-$nowTime*
  on:
    branch: master
branches:
  only:
  - master
  except:
  - /^(?i:untagged)-.*$/
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
